name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: git clone https://github.com/diem/diem/ -b diem-core-v1.2.0 ../diem && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
